#!/bin/bash
conffile=/u01/eirsapp/configuration/configuration.properties
typeset -A config # init array

while read line
do
    if echo $line | grep -F = &>/dev/null
    then
        varname=$(echo "$line" | cut -d '=' -f 1)
        config[$varname]=$(echo "$line" | cut -d '=' -f 2-)
    fi
done < $conffile
conn1="mysql -h${config[dbIp]} -P${config[dbPort]} -u${config[dbUsername]} -p${config[dbPassword]}"
conn2="mysql -h${config[dbIp]} -P${config[dbPort]} -u${config[dbUsername]} -p${config[dbPassword]} ${config[auddbName]}"
conn="mysql -h${config[dbIp]} -P${config[dbPort]} -u${config[dbUsername]} -p${config[dbPassword]} ${config[appdbName]}"

echo "creating app database."
${conn1} -e "CREATE DATABASE IF NOT EXISTS app;"
echo " app database successfully created!"
echo ${conn}
${conn}<<EOFMYSQL
CREATE TABLE IF NOT EXISTS active_foreign_imei_with_different_msisdn (
  id                       INT NOT NULL AUTO_INCREMENT,
  created_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified_on              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  tac                      VARCHAR(8),
  msisdn                   VARCHAR(20),
  failed_rule_id           INT DEFAULT 0,
  failed_rule_name         VARCHAR(50),
  imsi                     VARCHAR(20),
  mobile_operator          VARCHAR(20),
  create_filename          VARCHAR(100),
  update_filename          VARCHAR(100),
  updated_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  system_type              VARCHAR(50),
  action                   VARCHAR(50),
  period                   VARCHAR(50),
  failed_rule_date         TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  mobile_operator_id       INT DEFAULT 0,
  tax_paid                 INT DEFAULT 0,
  feature_name             VARCHAR(50),
  record_time              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  actual_imei              VARCHAR(20),
  record_type              VARCHAR(50),
  imei                     VARCHAR(20),
  raw_cdr_file_name        VARCHAR(100),
  imei_arrival_time        TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  source                   VARCHAR(20),
  update_raw_cdr_file_name VARCHAR(100),
  update_imei_arrival_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  update_source            VARCHAR(20),
  server_origin            VARCHAR(25),
  actual_operator          VARCHAR(20) DEFAULT NULL,
  test_imei                VARCHAR(20) DEFAULT NULL,
  is_used                  VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS active_imei_with_different_msisdn (
  id                       INT NOT NULL AUTO_INCREMENT,
  created_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified_on              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  tac                      VARCHAR(8),
  msisdn                   VARCHAR(20),
  failed_rule_id           INT DEFAULT 0,
  failed_rule_name         VARCHAR(50),
  imsi                     VARCHAR(20),
  mobile_operator          VARCHAR(20),
  create_filename          VARCHAR(100),
  update_filename          VARCHAR(100),
  updated_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  system_type              VARCHAR(50),
  action                   VARCHAR(50),
  period                   VARCHAR(50),
  failed_rule_date         TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  mobile_operator_id       INT DEFAULT 0,
  tax_paid                 INT DEFAULT 0,
  feature_name             VARCHAR(50),
  record_time              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  actual_imei              VARCHAR(20),
  record_type              VARCHAR(50),
  imei                     VARCHAR(20),
  raw_cdr_file_name        VARCHAR(100),
  imei_arrival_time        TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  source                   VARCHAR(20),
  update_raw_cdr_file_name VARCHAR(100),
  update_imei_arrival_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  update_source            VARCHAR(20),
  server_origin            VARCHAR(255),
  actual_operator          VARCHAR(20) DEFAULT NULL,
  test_imei                VARCHAR(20) DEFAULT NULL,
  is_used                  VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS active_unique_foreign_imei (
  id                       INT NOT NULL AUTO_INCREMENT,
  created_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified_on              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  foregin_value            VARCHAR(50),
  tac                      VARCHAR(8),
  msisdn                   VARCHAR(20),
  failed_rule_id           INT DEFAULT 0,
  failed_rule_name         VARCHAR(50),
  imsi                     VARCHAR(20),
  mobile_operator          VARCHAR(20),
  create_filename          VARCHAR(100),
  update_filename          VARCHAR(100),
  updated_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  system_type              VARCHAR(50),
  action                   VARCHAR(50),
  period                   VARCHAR(50),
  failed_rule_date         TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  mobile_operator_id       INT DEFAULT 0,
  tax_paid                 INT DEFAULT 0,
  feature_name             VARCHAR(50),
  record_time              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  actual_imei              VARCHAR(20),
  record_type              VARCHAR(50),
  imei                     VARCHAR(20),
  raw_cdr_file_name        VARCHAR(100),
  imei_arrival_time        TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  source                   VARCHAR(20),
  update_raw_cdr_file_name VARCHAR(100),
  update_imei_arrival_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  update_source            VARCHAR(20),
  server_origin            VARCHAR(25),
  actual_operator          VARCHAR(20) DEFAULT NULL,
  test_imei                VARCHAR(20) DEFAULT NULL,
  is_used                  VARCHAR(20) DEFAULT NULL,
  foreign_rule              VARCHAR(50)DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_imei (imei)
);
CREATE TABLE IF NOT EXISTS active_unique_imei (
  id                       INT NOT NULL AUTO_INCREMENT,
  created_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified_on              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  foregin_value            VARCHAR(50),
  tac                      VARCHAR(8),
  msisdn                   VARCHAR(20),
  failed_rule_id           INT DEFAULT 0,
  failed_rule_name         VARCHAR(50),
  imsi                     VARCHAR(20),
  mobile_operator          VARCHAR(20),
  create_filename          VARCHAR(100),
  update_filename          VARCHAR(100),
  updated_on               TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  system_type              VARCHAR(50),
  action                   VARCHAR(50),
  period                   VARCHAR(50),
  failed_rule_date         TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  mobile_operator_id       INT DEFAULT 0,
  tax_paid                 INT DEFAULT 0,
  feature_name             VARCHAR(50),
  record_time              TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  actual_imei              VARCHAR(20),
  record_type              VARCHAR(50),
  imei                     VARCHAR(20),
  raw_cdr_file_name        VARCHAR(100),
  imei_arrival_time        TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  source                   VARCHAR(20),
  update_raw_cdr_file_name VARCHAR(100),
  update_imei_arrival_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  update_source            VARCHAR(20),
  server_origin            VARCHAR(255),
  actual_operator          VARCHAR(20) DEFAULT NULL,
  test_imei                VARCHAR(20) DEFAULT NULL,
  is_used                  VARCHAR(20) DEFAULT NULL,
  foreign_rule              VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_imei (imei)
);
CREATE TABLE IF NOT EXISTS national_whitelist (
  national_whitelist_id             INT NOT NULL AUTO_INCREMENT,
  created_on                        DATETIME,
  modified_on                       DATETIME,
  foreign_rule                      VARCHAR(255),
  mobile_operator                   VARCHAR(255),
  period                            VARCHAR(255),
  tax_paid                          VARCHAR(255),
  created_filename                  VARCHAR(255),
  updated_filename                  VARCHAR(255),
  updated_on                        DATETIME,
  system_type                       VARCHAR(255),
  failed_rule_id                    INT,
  failed_rule_name                  VARCHAR(255),
  validity_flag                     TINYINT(1),
  tac                               VARCHAR(255),
  action                            VARCHAR(255),
  failed_rule_date                  DATETIME,
  feature_name                      VARCHAR(255),
  record_time                       DATETIME,
  actual_imei                       VARCHAR(255),
  record_type                       VARCHAR(255),
  imei                              VARCHAR(255),
  raw_cdr_file_name                 VARCHAR(255),
  imei_arrival_time                 DATETIME,
  source                            VARCHAR(255),
  update_raw_cdr_file_name          VARCHAR(255),
  update_imei_arrival_time          DATETIME,
  update_source                     VARCHAR(255),
  server_origin                     VARCHAR(255),
  list_type                         VARCHAR(255),
  type_of_entry                     VARCHAR(255),
  national_white_list_created_date  DATETIME,
  reason                            VARCHAR(255),
  imsi                              VARCHAR(255),
  msisdn                            VARCHAR(255),
  created_on_date                   DATE,
  device_type                       VARCHAR(255),
  actual_operator                   VARCHAR(255),
  is_test_imei                      VARCHAR(255),
  is_used_device_imei               VARCHAR(255),
  reason_for_invalid_imei           VARCHAR(255),
  PRIMARY KEY (national_whitelist_id),
  UNIQUE KEY unique_imei (imei)
);
CREATE TABLE IF NOT EXISTS exception_list (
  exception_list_id           INT NOT NULL AUTO_INCREMENT,
  created_on                  DATETIME,
  modified_on                 DATETIME,
  tac                         VARCHAR(255),
  msisdn                      VARCHAR(255),
  failed_rule_id              INT,
  failed_rule_name            VARCHAR(255),
  imsi                        VARCHAR(255),
  mobile_operator             VARCHAR(255),
  created_filename            VARCHAR(255),
  updated_filename            VARCHAR(255),
  updated_on                  DATETIME,
  system_type                 VARCHAR(255),
  action                      VARCHAR(255),
  period                      VARCHAR(255),
  failed_rule_date            DATETIME,
  tax_paid                    INT,
  feature_name                VARCHAR(255),
  record_time                 DATETIME,
  actual_imei                 VARCHAR(255),
  record_type                 VARCHAR(255),
  imei                        VARCHAR(255),
  raw_cdr_file_name           VARCHAR(255),
  imei_arrival_time           DATETIME,
  source                      VARCHAR(255),
  update_raw_cdr_file_name    VARCHAR(255),
  update_imei_arrival_time    DATETIME,
  update_source               VARCHAR(255),
  server_origin               VARCHAR(255),
  reason_for_invalid_imei     VARCHAR(255),
  foreign_value                ARCHAR(255),
  validity_flag               TINYINT(1),
  device_type                 VARCHAR(255),
  exception_list_created_date DATETIME,
  actual_operator             VARCHAR(255),
  is_test_imei                VARCHAR(255),
  list_type                   VARCHAR(255),
  is_used_device_imei         VARCHAR(255),
  foreign_rule varchar(255),
  PRIMARY KEY (exception_list_id),
  UNIQUE KEY unique_imei_msisdn (imei, msisdn)
);
CREATE TABLE IF NOT EXISTS foreign_whitelist (
  foreign_whitelist_id              INT NOT NULL AUTO_INCREMENT,
  created_on                        DATETIME,
  modified_on                       DATETIME,
  foreign_rule                      VARCHAR(255),
  mobile_operator                   VARCHAR(255),
  period                            VARCHAR(255),
  tax_paid                          VARCHAR(255),
  created_filename                  VARCHAR(255),
  updated_filename                  VARCHAR(255),
  updated_on                        DATETIME,
  system_type                       VARCHAR(255),
  failed_rule_id                    INT,
  failed_rule_name                  VARCHAR(255),
  validity_flag                     TINYINT(1),
  tac                               VARCHAR(255),
  action                            VARCHAR(255),
  failed_rule_date                  DATETIME,
  feature_name                      VARCHAR(255),
  record_time                       DATETIME,
  actual_imei                       VARCHAR(255),
  record_type                       VARCHAR(255),
  imei                              VARCHAR(255),
  raw_cdr_file_name                 VARCHAR(255),
  imei_arrival_time                 DATETIME,
  source                            VARCHAR(255),
  update_raw_cdr_file_name          VARCHAR(255),
  update_imei_arrival_time          DATETIME,
  update_source                     VARCHAR(255),
  server_origin                     VARCHAR(255),
  list_type                         VARCHAR(255),
  type_of_entry                     VARCHAR(255),
  national_white_list_created_date  DATETIME,
  foreign_white_list_created_date  DATETIME,
  reason_for_invalid_imei           VARCHAR(255),
  reason                            VARCHAR(255),
  imsi                              VARCHAR(255),
  msisdn                            VARCHAR(255),
  created_on_date                   DATE,
  device_type                       VARCHAR(255),
  actual_operator                   VARCHAR(255),
  is_test_imei                      VARCHAR(255),
  is_used_device_imei               VARCHAR(255),
  PRIMARY KEY (foreign_whitelist_id),
  UNIQUE KEY unique_imei (imei)
);
CREATE TABLE IF NOT EXISTS foreign_exception_list (
  foreign_exception_list_id   INT NOT NULL AUTO_INCREMENT,
  created_on                  DATETIME,
  modified_on                 DATETIME,
  tac                         VARCHAR(255),
  msisdn                      VARCHAR(255),
  failed_rule_id              INT,
  failed_rule_name            VARCHAR(255),
  imsi                        VARCHAR(255),
  mobile_operator             VARCHAR(255),
  created_filename            VARCHAR(255),
  updated_filename            VARCHAR(255),
  updated_on                  DATETIME,
  system_type                 VARCHAR(255),
  action                      VARCHAR(255),
  period                      VARCHAR(255),
  failed_rule_date            DATETIME,
  tax_paid                    INT,
  feature_name                VARCHAR(255),
  record_time                 DATETIME,
  actual_imei                 VARCHAR(255),
  record_type                 VARCHAR(255),
  imei                        VARCHAR(255),
  raw_cdr_file_name           VARCHAR(255),
  imei_arrival_time           DATETIME,
  source                      VARCHAR(255),
  update_raw_cdr_file_name    VARCHAR(255),
  update_imei_arrival_time    DATETIME,
  update_source               VARCHAR(255),
  server_origin               VARCHAR(255),
  reason_for_invalid_imei     VARCHAR(255),
  foreign_value                ARCHAR(255),
  validity_flag               TINYINT(1),
  exception_list_created_date DATETIME,
  device_type                 VARCHAR(255),
  actual_operator             VARCHAR(255),
  is_test_imei                VARCHAR(255),
  list_type                   VARCHAR(255),
  is_used_device_imei         VARCHAR(255),
  foreign_rule varchar(255),
  PRIMARY KEY (foreign_exception_list_id),
  UNIQUE KEY unique_combination (imei, msisdn)
);
CREATE TABLE sys_param (
  created_on   TIMESTAMP,
  description  VARCHAR(255),
  modified_on  TIMESTAMP,
  tag          VARCHAR(255),
  type         INT,
  value        VARCHAR(255),
  active       INT,
  feature_name VARCHAR(255),
  remark       VARCHAR(255),
  user_type    VARCHAR(255),
  modified_by  VARCHAR(255),
  id           INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

EOFMYSQL

echo "creating aud database."
${conn} -e "CREATE DATABASE if not exists  aud;"
echo " aud database successfully created!"

${conn2} <<EOFMYSQL
CREATE TABLE IF NOT EXISTS modules_audit_trail (
  id             INT NOT NULL AUTO_INCREMENT,
  created_on     TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified_on    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  execution_time INT,
  status_code    INT,
  status         VARCHAR(10),
  error_message  VARCHAR(255),
  module_name    VARCHAR(50),
  feature_name   VARCHAR(50),
  action         VARCHAR(20),
  count          INT,
  info           VARCHAR(255),
  server_name    VARCHAR(30),
  PRIMARY KEY (id)
);

INSERT INTO rule (description, modified_on, name, output, state, modified_by)
VALUES
('This Rule checks if imei length is valid', '2023-06-29 14:26:44', 'IMEI_LENGTH_NATIONAL_WHITELIST', 'Yes', 'Enabled', 'system'),
('The rule checks if the IMEI is blank or all zeros', '2022-11-17 11:25:24', 'IMEI_NULL', 'No', 'Enabled', NULL),
('This Rule checks if imei is test imei', '2023-06-29 14:26:44', 'IMEI_TEST', 'Yes', 'Enabled', 'system'),
('This Rule checks if tac is valid', '2023-06-30 11:04:09', 'VALID_TAC', 'Yes', 'Enabled', 'system');


INSERT INTO feature_rule (feature, grace_action, name, post_grace_action, rule_order, user_type, failed_rule_action_grace, failed_rule_action_post_grace, output, rule_message, modified_by)
VALUES
('national_whitelist', 'Reject', 'IMEI_NULL', 'Reject', 1, 'default', 'Rule', 'Rule', 'Yes', NULL, 'system'),
('national_whitelist', 'Reject', 'IMEI_TEST', 'Reject', 2, 'default', 'Rule', 'Rule', 'Yes', NULL, 'system'),
('national_whitelist', 'Rule', 'IMEI_LENGTH_NATIONAL_WHITELIST', 'Rule', 3, 'default', 'Reject', 'Reject', 'Yes', NULL, 'system'),
('national_whitelist', 'Reject', 'VALID_TAC', 'Reject', 0, 'default', 'Rule', 'Rule', 'Yes', NULL, 'system');
('foreign_whitelist', 'Reject', 'IMEI_NULL', 'Reject', 1, 'default', 'Rule', 'Rule', 'Yes', NULL, 'system'),
('foreign_whitelist', 'Reject', 'IMEI_TEST', 'Reject', 2, 'default', 'Rule', 'Rule', 'Yes', NULL, 'system'),
('foreign_whitelist', 'Rule', 'IMEI_LENGTH_NATIONAL_WHITELIST', 'Rule', 3, 'default', 'Reject', 'Reject', 'Yes', NULL, 'system'),
('foreign_whitelist', 'Reject', 'VALID_TAC', 'Reject', 0, 'default', 'Rule', 'Rule', 'Yes', NULL, 'system');
EOFMYSQL
echo "tables creation completed."
